// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"github.com/google/uuid"
)

type Token struct {
	ID     int32
	UserID uuid.NullUUID
	Token  string
}

type User struct {
	ID       uuid.UUID
	Username string
	Email    string
	Password string
}
